In [13]:
#Dependencies
import glob
import pandas as pd
import numpy as np

In [39]:
#Glob data to combine all CSV's
path= r'C:\Users\Phil\Desktop\Project\Resources'
all_files=glob.glob(path+"/*.csv")
li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)

frame = pd.concat(li, axis=0, ignore_index=True)
#Column clean up and formatting
frame=frame.rename(columns={"Open": "Open in USD",
                                "High": "High in USD",
                                "Low": "Low in USD",
                                "Close": "Close in USD",
                                "Adj Close": "Adj Close in USD",
                                "Volume": "Volume in Billions"})
frame["Open in USD"] = frame["Open in USD"].map("{:.2f}".format)
frame["High in USD"] = frame["High in USD"].map("{:.2f}".format)
frame["Low in USD"] = frame["Low in USD"].map("{:.2f}".format)
frame["Close in USD"] = frame["Close in USD"].map("{:.2f}".format)
frame["Adj Close in USD"] = frame["Adj Close in USD"].map("{:.2f}".format)
frame["Volume in Billions"]=frame["Volume in Billions"]/1000000000
frame["Volume in Billions"] = frame["Volume in Billions"].map("{:.2f}".format)
#Write CSV
#frame.to_csv("Output/CryptoCurrency.csv", index=False, header=True)
frame["Open in USD"]=frame["Open in USD"].astype(str).astype(float)
frame["High in USD"]=frame["High in USD"].astype(str).astype(float)
frame["Low in USD"]=frame["Low in USD"].astype(str).astype(float)
frame["Close in USD"]=frame["Close in USD"].astype(str).astype(float)
frame["Adj Close in USD"]=frame["Adj Close in USD"].astype(str).astype(float)
frame["Volume in Billions"]=frame["Volume in Billions"].astype(str).astype(float)
frame.dtypes
frame.head()

,Ticker,Date,Open in USD,High in USD,Low in USD,Close in USD,Adj Close in USD,Volume in Billions
0,BCH,7/1/2017,555.89,578.97,217.06,294.46,294.46,0.01
1,BCH,8/1/2017,294.60,1091.97,200.98,588.17,588.17,17.12
2,BCH,9/1/2017,588.40,707.98,301.69,432.63,432.63,11.31
3,BCH,10/1/2017,433.38,526.12,289.04,439.05,439.05,10.86
4,BCH,11/1/2017,438.30,2477.65,437.91,1256.33,1256.33,66.78

In [60]:
crypto_data=frame[["Ticker", "Open in USD", "High in USD", "Low in USD", "Close in USD", "Adj Close in USD", "Volume in Billions"]]
crypto_group=crypto_data.groupby(["Ticker"])
volume_sum=crypto_group.sum()
volume_sum=volume_sum["Volume in Billions"]
volume_mean=crypto_group.mean()
volume_mean=volume_mean["Volume in Billions"]
volume_max=crypto_group.max()
volume_max=volume_max["Volume in Billions"]
volume_min=crypto_group.min()
volume_min=volume_min["Volume in Billions"]
volume_var=crypto_group.var()
volume_var=volume_var["Volume in Billions"]
volume_std=crypto_group.std()
volume_std=volume_std["Volume in Billions"]
volume_sem=crypto_group.sem()
volume_sem=volume_sem["Volume in Billions"]
volume_df=pd.DataFrame({"Volume Sum in Billions": volume_sum,
                        "Volume Average": volume_mean,
                        "Volume Max": volume_max,
                       "Volume Min": volume_min,
                       "Volume Variance": volume_var,
                       "Volume Std. Dev": volume_std,
                       "Volume Std. Err": volume_sem})
volume_df

,Volume Sum in Billions,Volume Average,Volume Max,Volume Min,Volume Variance,Volume Std. Dev,Volume Std. Err
Ticker,,,,,,,
BCH,1792.98,43.731220,175.00,0.01,1503.901536,38.780169,6.056445
BNB,209.92,5.120000,15.32,0.00,19.130865,4.373884,0.683086
BTC,18450.20,302.462295,1290.00,1.81,129975.851071,360.521637,46.160066
ETH,7809.93,128.031639,578.00,0.01,25327.863341,159.147301,20.376724
LTC,2267.19,37.167049,159.00,0.04,2107.472414,45.907215,5.877817
USDT,19813.05,330.217500,1642.54,0.00,227781.627751,477.264735,61.614612
XRP,1451.30,24.188333,105.60,0.01,694.281414,26.349220,3.401670

In [54]:
open_sum=crypto_group.sum()
open_sum=open_sum["Open in USD"]
open_mean=crypto_group.mean()
open_mean=open_mean["Open in USD"]
open_max=crypto_group.max()
open_max=open_max["Open in USD"]
open_min=crypto_group.min()
open_min=open_min["Open in USD"]
open_var=crypto_group.var()
open_var=open_var["Open in USD"]
open_std=crypto_group.std()
open_std=open_std["Open in USD"]
open_sem=crypto_group.sem()
open_sem=open_sem["Open in USD"]
open_df=pd.DataFrame({"Open Sum": open_sum,
                        "Open Average": open_mean,
                        "Open Max": open_max,
                       "Open Min": open_min,
                       "Open Variance": open_var,
                       "Open Std. Dev": open_std,
                       "Open Std. Err": open_sem})
open_df

,Open Sum,Open Average,Open Max,Open Min,Open Variance,Open Std. Dev,Open Std. Err
Ticker,,,,,,,
BCH,21067.51,43.731220,175.00,0.01,1503.901536,38.780169,6.056445
BNB,586.34,5.120000,15.32,0.00,19.130865,4.373884,0.683086
BTC,333009.34,302.462295,1290.00,1.81,129975.851071,360.521637,46.160066
ETH,13566.61,128.031639,578.00,0.01,25327.863341,159.147301,20.376724
LTC,3181.90,37.167049,159.00,0.04,2107.472414,45.907215,5.877817
USDT,60.03,330.217500,1642.54,0.00,227781.627751,477.264735,61.614612
XRP,16.77,24.188333,105.60,0.01,694.281414,26.349220,3.401670

In [55]:
high_sum=crypto_group.sum()
high_sum=high_sum["High in USD"]
high_mean=crypto_group.mean()
high_mean=high_mean["High in USD"]
high_max=crypto_group.max()
high_max=high_max["High in USD"]
high_min=crypto_group.min()
high_min=high_min["High in USD"]
high_var=crypto_group.var()
high_var=high_var["High in USD"]
high_std=crypto_group.std()
high_std=high_std["High in USD"]
high_sem=crypto_group.sem()
high_sem=high_sem["High in USD"]
high_df=pd.DataFrame({"High Sum": high_sum,
                        "High Average": high_mean,
                        "High Max": high_max,
                       "High Min": high_min,
                       "High Variance": high_var,
                       "High Std. Dev": high_std,
                       "High Std. Err": high_sem})
high_df

,High Sum,High Average,High Max,High Min,High Variance,High Std. Dev,High Std. Err
Ticker,,,,,,,
BCH,31440.04,766.830244,4355.62,157.65,7.382782e+05,859.231166,134.189364
BNB,738.65,18.015854,39.57,0.12,9.896923e+01,9.948328,1.553668
BTC,405889.29,6653.922787,20089.00,439.65,2.512644e+07,5012.627899,641.801236
ETH,17495.06,286.804262,1432.88,1.05,8.527163e+04,292.013070,37.388442
LTC,4308.30,70.627869,375.29,3.45,5.608047e+03,74.886892,9.588284
USDT,61.86,1.031000,1.21,1.00,1.243051e-03,0.035257,0.004552
XRP,24.45,0.407500,3.84,0.01,3.909445e-01,0.625256,0.080720

In [56]:
low_sum=crypto_group.sum()
low_sum=low_sum["Low in USD"]
low_mean=crypto_group.mean()
low_mean=low_mean["Low in USD"]
low_max=crypto_group.max()
low_max=low_max["Low in USD"]
low_min=crypto_group.min()
low_min=low_min["Low in USD"]
low_var=crypto_group.var()
low_var=low_var["Low in USD"]
low_std=crypto_group.std()
low_std=low_std["Low in USD"]
low_sem=crypto_group.sem()
low_sem=low_sem["Low in USD"]
low_df=pd.DataFrame({"Low Sum": low_sum,
                        "Low Average": low_mean,
                        "Low Max": low_max,
                       "Low Min": low_min,
                       "Low Variance": low_var,
                       "Low Std. Dev": low_std,
                       "Low Std. Err": low_sem})
low_df

,Low Sum,Low Average,Low Max,Low Min,Low Variance,Low Std. Dev,Low Std. Err
Ticker,,,,,,,
BCH,14721.41,359.058780,1361.02,75.08,8.280792e+04,287.763645,44.941131
BNB,486.66,11.869756,30.46,0.10,6.074604e+01,7.793975,1.217214
BTC,284718.93,4667.523443,12896.59,301.00,1.221868e+07,3495.523355,447.555904
ETH,10498.76,172.110820,742.00,0.73,2.602218e+04,161.313926,20.654132
LTC,2455.52,40.254426,141.01,2.92,1.126784e+03,33.567597,4.297890
USDT,58.54,0.975667,1.00,0.85,8.114124e-04,0.028485,0.003677
XRP,12.00,0.200000,0.90,0.00,3.177627e-02,0.178259,0.023013

In [57]:
close_sum=crypto_group.sum()
close_sum=close_sum["Close in USD"]
close_mean=crypto_group.mean()
close_mean=close_mean["Close in USD"]
close_max=crypto_group.max()
close_max=close_max["Close in USD"]
close_min=crypto_group.min()
close_min=close_min["Close in USD"]
close_var=crypto_group.var()
close_var=close_var["Close in USD"]
close_std=crypto_group.std()
close_std=close_std["Close in USD"]
close_sem=crypto_group.sem()
close_sem=close_sem["Close in USD"]
close_df=pd.DataFrame({"Close Sum": close_sum,
                        "Close Average": close_mean,
                        "Close Max": close_max,
                       "Close Min": close_min,
                       "Close Variance": close_var,
                       "Close Std. Dev": close_std,
                       "Close Std. Err": close_sem})
close_df

,Close Sum,Close Average,Close Max,Close Min,Close Variance,Close Std. Dev,Close Std. Err
Ticker,,,,,,,
BCH,20644.94,503.535122,2533.01,114.81,2.260771e+05,475.475679,74.256826
BNB,616.63,15.039756,32.75,0.10,7.796319e+01,8.829677,1.378964
BTC,345878.78,5670.143934,14156.40,368.77,1.691555e+07,4112.851838,526.596717
ETH,13972.51,229.057541,1118.31,0.87,5.093516e+04,225.688193,28.896412
LTC,3235.29,53.037541,232.10,3.05,2.407531e+03,49.066602,6.282335
USDT,60.04,1.000667,1.04,0.94,1.114124e-04,0.010555,0.001363
XRP,17.03,0.283833,2.30,0.00,1.241901e-01,0.352406,0.045495

In [59]:
adjclose_sum=crypto_group.sum()
adjclose_sum=adjclose_sum["Adj Close in USD"]
adjclose_mean=crypto_group.mean()
adjclose_mean=adjclose_mean["Adj Close in USD"]
adjclose_max=crypto_group.max()
adjclose_max=adjclose_max["Adj Close in USD"]
adjclose_min=crypto_group.min()
adjclose_min=adjclose_min["Adj Close in USD"]
adjclose_var=crypto_group.var()
adjclose_var=adjclose_var["Adj Close in USD"]
adjclose_std=crypto_group.std()
adjclose_std=adjclose_std["Adj Close in USD"]
adjclose_sem=crypto_group.sem()
adjclose_sem=adjclose_sem["Adj Close in USD"]
adjclose_df=pd.DataFrame({"Adj Close Sum": adjclose_sum,
                        "Adj Close Average": adjclose_mean,
                        "Adj Close Max": adjclose_max,
                       "Adj Close Min": adjclose_min,
                       "Adj Close Variance": adjclose_var,
                       "Adj Close Std. Dev": adjclose_std,
                       "Adj Close Std. Err": adjclose_sem})
adjclose_df

,Adj Close Sum,Adj Close Average,Adj Close Max,Adj Close Min,Adj Close Variance,Adj Close Std. Dev,Adj Close Std. Err
Ticker,,,,,,,
BCH,20644.94,503.535122,2533.01,114.81,2.260771e+05,475.475679,74.256826
BNB,616.63,15.039756,32.75,0.10,7.796319e+01,8.829677,1.378964
BTC,345878.78,5670.143934,14156.40,368.77,1.691555e+07,4112.851838,526.596717
ETH,13972.51,229.057541,1118.31,0.87,5.093516e+04,225.688193,28.896412
LTC,3235.29,53.037541,232.10,3.05,2.407531e+03,49.066602,6.282335
USDT,60.04,1.000667,1.04,0.94,1.114124e-04,0.010555,0.001363
XRP,17.03,0.283833,2.30,0.00,1.241901e-01,0.352406,0.045495