In [33]:
#Dependencies
import glob
import pandas as pd
import numpy as np
import scipy.stats as st

In [2]:
#Glob data to combine all CSV's
path= r'C:\Users\Phil\Desktop\Project\Resources'
all_files=glob.glob(path+"/*.csv")
li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)

frame = pd.concat(li, axis=0, ignore_index=True)
#Column clean up and formatting
frame=frame.rename(columns={"Open": "Open in USD",
                                "High": "High in USD",
                                "Low": "Low in USD",
                                "Close": "Close in USD",
                                "Adj Close": "Adj Close in USD",
                                "Volume": "Volume in Billions"})
frame["Open in USD"] = frame["Open in USD"].map("{:.2f}".format)
frame["High in USD"] = frame["High in USD"].map("{:.2f}".format)
frame["Low in USD"] = frame["Low in USD"].map("{:.2f}".format)
frame["Close in USD"] = frame["Close in USD"].map("{:.2f}".format)
frame["Adj Close in USD"] = frame["Adj Close in USD"].map("{:.2f}".format)
frame["Volume in Billions"]=frame["Volume in Billions"]/1000000000
frame["Volume in Billions"] = frame["Volume in Billions"].map("{:.2f}".format)
#Write CSV
#frame.to_csv("Output/CryptoCurrency.csv", index=False, header=True)
frame["Open in USD"]=frame["Open in USD"].astype(str).astype(float)
frame["High in USD"]=frame["High in USD"].astype(str).astype(float)
frame["Low in USD"]=frame["Low in USD"].astype(str).astype(float)
frame["Close in USD"]=frame["Close in USD"].astype(str).astype(float)
frame["Adj Close in USD"]=frame["Adj Close in USD"].astype(str).astype(float)
frame["Volume in Billions"]=frame["Volume in Billions"].astype(str).astype(float)
frame.dtypes
frame.head()

,Ticker,Date,Open in USD,High in USD,Low in USD,Close in USD,Adj Close in USD,Volume in Billions
0,BCH,7/1/2017,555.89,578.97,217.06,294.46,294.46,0.01
1,BCH,8/1/2017,294.60,1091.97,200.98,588.17,588.17,17.12
2,BCH,9/1/2017,588.40,707.98,301.69,432.63,432.63,11.31
3,BCH,10/1/2017,433.38,526.12,289.04,439.05,439.05,10.86
4,BCH,11/1/2017,438.30,2477.65,437.91,1256.33,1256.33,66.78

In [34]:
#Data frame for Volume of Trades for Cryptos included Sum, Mean, Median, Max, Min, Variance and Standard Deviation.
vol_clean=pd.DataFrame(crypto_data.groupby("Ticker").agg({'Volume in Billions':[np.sum,
                                                                               np.mean,
                                                                               np.median,
                                                                               np.max,
                                                                               np.min,
                                                                               np.var,
                                                                               np.std,
                                                                               st.sem]}))
vol_clean.style.format("{:.2f}")

In [35]:
#Data frame for Opening details for Cryptos included Sum, Mean, Median, Max, Min, Variance and Standard Deviation.
open_clean=pd.DataFrame(crypto_data.groupby("Ticker").agg({'Open in USD':[np.sum,
                                                                               np.mean,
                                                                               np.median,
                                                                               np.max,
                                                                               np.min,
                                                                               np.var,
                                                                               np.std,
                                                                               st.sem]}))
open_clean.style.format("{:.2f}")

In [36]:
#Data frame for Closing details for Cryptos included Sum, Mean, Median, Max, Min, Variance and Standard Deviation.
close_clean=pd.DataFrame(crypto_data.groupby("Ticker").agg({'Close in USD':[np.sum,
                                                                               np.mean,
                                                                               np.median,
                                                                               np.max,
                                                                               np.min,
                                                                               np.var,
                                                                               np.std,
                                                                               st.sem]}))
close_clean.style.format("{:.2f}")

In [37]:
#Data frame for Crypto Highs included Sum, Mean, Median, Max, Min, Variance and Standard Deviation.
high_clean=pd.DataFrame(crypto_data.groupby("Ticker").agg({'High in USD':[np.sum,
                                                                               np.mean,
                                                                               np.median,
                                                                               np.max,
                                                                               np.min,
                                                                               np.var,
                                                                               np.std,
                                                                               st.sem]}))
high_clean.style.format("{:.2f}")

In [38]:
#Data frame for Crypto Lows included Sum, Mean, Median, Max, Min, Variance and Standard Deviation.
low_clean=pd.DataFrame(crypto_data.groupby("Ticker").agg({'Low in USD':[np.sum,
                                                                               np.mean,
                                                                               np.median,
                                                                               np.max,
                                                                               np.min,
                                                                               np.var,
                                                                               np.std,
                                                                               st.sem]}))
low_clean.style.format("{:.2f}")